## Persiapan Data

In [ ]:
# Import Library Standard
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Import Library Sklearn
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.naive_bayes import MultinomialNB

# Import Library Sklearn (Evaluasi Tak Berperingkat)
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score


# Import Library Sklearn (Evaluasi Berperingkat)
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

# Import Library untuk Stemming
!pip install Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

Collecting Sastrawi
  Downloading https://files.pythonhosted.org/packages/6f/4b/bab676953da3103003730b8fcdfadbdd20f333d4add10af949dd5c51e6ed/Sastrawi-1.0.1-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 24.1MB/s
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
# Read Dataset
data = pd.read_excel('dataset1.xlsx')
# data = pd.read_csv('dataset2.csv')
data.head()

,Topic,Title,Content
0,Politik,"Pelanggaran Pemilu, Tiga Caleg di Sulteng Dipr...","Komisioner Bawaslu Sigi, Sulawesi Tengah, Agus..."
1,Politik,"Pemilu Susulan di Kota Jayapura, Suara Jokowi ...",Walaupun dua dari lima distrik melakukan pemil...
2,Politik,"Tsamara Amany Dipinang, Pengurus PSI Daerah Me...","Tsamara Amany, politisi Partai Solidaritas Ind..."
3,Politik,Ada 47 TPS di Sulawesi Utara Berpotensi Pemili...,Badan Pengawas Pemilu (Bawaslu) Provinsi Sulaw...
4,Politik,Ketua KPPS di Sleman Ditemukan Tewas Gantung D...,"Tugiman, Ketua Kelompok Penyelenggara Pemungut..."

In [ ]:
# Label Mapping
# data['Topic'] = data['Topic'].map({'Politik':0, 'Teknologi':1, 'Travel':2})
# data.head()

In [ ]:
# Ukuran Dataset
print('Ukuran dataset:', data.shape)

Ukuran dataset: (60, 3)

In [ ]:
# Pembagian data training & testing
x_train, x_test, y_train, y_test = train_test_split(data['Content'], data['Topic'], train_size=0.5, test_size=0.16)

In [ ]:
train_data = pd.DataFrame({'teks':x_train, 'label':y_train})
test_data = pd.DataFrame({'teks':x_test, 'label':y_test})

In [ ]:
train_data.head()

                                                 teks      label
28  Masyarakat Indonesia menggunakan hak pilihnya ...  Teknologi
16  Pemungutan suara Pemilu 2019 telah usai. Tapi ...    Politik
47  Pemerintah Kota Banjarmasin baru saja menyeles...     Travel
18  Isu kecurangan di Pemilu 2019 terus menyeruak....    Politik
49  Bila biasanya mesin fotokopi terdapat di kios-...     Travel

In [ ]:
test_data.head()

                                                 teks      label
30  Kemajuan teknologi memudahkan dan mengubah keb...  Teknologi
38  Kamu mungkin pernah merasa kesulitan untuk ber...  Teknologi
14  KPU memberikan klarifikasi mengenai banyaknya ...    Politik
53  Untuk mendukung pengembangan pariwisata Sulawe...     Travel
0   Komisioner Bawaslu Sigi, Sulawesi Tengah, Agus...    Politik

In [ ]:
# Ukuran Data Training & Testing
print('Ukuran data train:', train_data.shape)
print('Ukuran data test:', test_data.shape)
n_train = train_data.shape[0]
n_test = test_data.shape[0]

Ukuran data train: (30, 2)
Ukuran data test: (10, 2)

In [ ]:
sparse_data = pd.concat([train_data, test_data], ignore_index=True)
sparse_data.head()

                                                teks      label
0  Masyarakat Indonesia menggunakan hak pilihnya ...  Teknologi
1  Pemungutan suara Pemilu 2019 telah usai. Tapi ...    Politik
2  Pemerintah Kota Banjarmasin baru saja menyeles...     Travel
3  Isu kecurangan di Pemilu 2019 terus menyeruak....    Politik
4  Bila biasanya mesin fotokopi terdapat di kios-...     Travel

In [ ]:
# Ukuran Sparse Data
print('Ukuran sparse data:', sparse_data.shape)
n_document = sparse_data.shape[0]

Ukuran sparse data: (40, 2)

## Stemming Dengan Stopword

### Preprocessing

**Stemming**

In [ ]:
# Create stemmer
stemmerFactory = StemmerFactory()
stemmer = stemmerFactory.create_stemmer()

In [ ]:
# Stem Process
for row in range(n_document):
  sparse_data.loc[row, 'teks'] = stemmer.stem(sparse_data.loc[row, 'teks'])

In [ ]:
sparse_data.head()

                                                teks      label
0  masyarakat indonesia guna hak pilih dalam milu...  Teknologi
1  mungut suara milu 2019 telah usai tapi duka ma...    Politik
2  perintah kota banjarmasin baru saja selesai de...     Travel
3  isu curang di milu 2019 terus seruak dua timse...    Politik
4  bila biasa mesin fotokopi dapat di kios yang t...     Travel

### Perhitungan Bobot

In [ ]:
vectorizer = CountVectorizer()
tf = vectorizer.fit_transform(sparse_data['teks'])
print('Jumlah dokumen:', tf.shape[0])
print('Jumlah term:', tf.shape[1])

Jumlah dokumen: 40
Jumlah term: 2284

In [ ]:
print('Daftar Term:')
vectorizer.get_feature_names()

Daftar Term:

['00',
 '000',
 '02',
 '03',
 '030',
 '04',
 '08',
 '09',
 '10',
 '100',
 '105',
 '11',
 '113',
 '12',
 '120',
 '13',
 '14',
 '144',
 '15',
 '150',
 '16',
 '17',
 '1723',
 '18',
 '19',
 '191',
 '1958',
 '1997',
 '20',
 '200',
 '2004',
 '2005',
 '2007',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '21',
 '210',
 '212',
 '218',
 '22',
 '23',
 '237',
 '24',
 '241',
 '247',
 '25',
 '250',
 '26',
 '28',
 '29',
 '30',
 '300',
 '31',
 '330',
 '34',
 '35',
 '36',
 '360',
 '366',
 '37',
 '38',
 '39',
 '3d',
 '40',
 '400',
 '420',
 '43',
 '44',
 '45',
 '46',
 '47',
 '50',
 '500',
 '51',
 '52',
 '53',
 '546',
 '55',
 '56',
 '562',
 '57',
 '579',
 '585',
 '59',
 '60',
 '600',
 '63',
 '630',
 '64',
 '640',
 '65',
 '650',
 '6703',
 '6s',
 '70',
 '75',
 '750',
 '79',
 '80',
 '800an',
 '810',
 '82',
 '835',
 '84',
 '85',
 '87',
 '870',
 '883',
 '893',
 '90',
 '94',
 '97',
 'abad',
 'abadi',
 'abdul',
 'academy',
 'acara',
 'action',
 'ada',
 'adalah',
 'adapun',
 'adik',
 'adil',
 'adopsi',
 'adriani',
 'aertembaga',
 'agam',
 'agar',
 'agus',
 'agustus',
 'ahli',
 'ai',
 'air',
 'airasia',
 'aircraft',
 'airlines',
 'airport',
 'airportnya',
 'airspace',
 'aja',
 'ajaib',
 'ajak',
 'ajar',
 'aju',
 'akan',
 'akbar',
 'akhir',
 'akibat',
 'akses',
 'aksesibilitas',
 'aktif',
 'aktivitas',
 'aku',
 'akun',
 'al',
 'alam',
 'alami',
 'alas',
 'alat',
 'algorithm',
 'algoritma',
 'alhasil',
 'alias',
 'alibaba',
 'alih',
 'alir',
 'alokasi',
 'alonissos',
 'aman',
 'amanah',
 'amat',
 'amazon',
 'ambil',
 'amenitas',
 'amerika',
 'amien',
 'amin',
 'ampolin',
 'anak',
 'anantia',
 'and',
 'anda',
 'andal',
 'android',
 'andy',
 'anggap',
 'anggar',
 'anggota',
 'anggur',
 'angka',
 'angkasa',
 'angota',
 'annapurna',
 'antar',
 'antara',
 'antarmuka',
 'antik',
 'antisipasi',
 'antre',
 'antusias',
 'anyar',
 'ap',
 'apa',
 'apabila',
 'aparat',
 'api',
 'aplikasi',
 'app',
 'apple',
 'apreasi',
 'apresiasi',
 'april',
 'ar',
 'arah',
 'arcade',
 'area',
 'arena',
 'arief',
 'arkeolog',
 'arrival',
 'arsitek',
 'artefak',
 'arti',
 'artificial',
 'as',
 'asa',
 'asah',
 'asal',
 'asean',
 'aset',
 'asing',
 'asosiasi',
 'aspek',
 'associated',
 'asuransi',
 'atar',
 'atas',
 'atau',
 'athena',
 'atk',
 'atm',
 'atmosfer',
 'atraksi',
 'atribut',
 'atta',
 'atur',
 'audio',
 'augmented',
 'avsec',
 'awak',
 'awal',
 'awaluddin',
 'awas',
 'awat',
 'ayam',
 'ayun',
 'azis',
 'aziz',
 'b2b',
 'baca',
 'bach',
 'backend',
 'badai',
 'badan',
 'bagai',
 'bagaimana',
 'bagasi',
 'baggage',
 'bagi',
 'bagus',
 'bahagia',
 'bahan',
 'bahas',
 'bahasa',
 'bahkan',
 'bahwa',
 'baik',
 'baja',
 'baju',
 'bak',
 'bakal',
 'bakar',
 'bakat',
 'bal',
 'balairung',
 'balik',
 'bandar',
 'bandara',
 'bandel',
 'banding',
 'bandung',
 'banget',
 'bangga',
 'bangkai',
 'bangsa',
 'bangun',
 'banjarhits',
 'banjarmasin',
 'banjir',
 'bantu',
 'banyak',
 'barang',
 'barat',
 'baring',
 'baru',
 'bas',
 'basiruddin',
 'basirudin',
 'basket',
 'batal',
 'batas',
 'baterai',
 'batu',
 'bawa',
 'bawah',
 'bawaslu',
 'bayar',
 'bayi',
 'bbm',
 'beach4teach',
 'bebas',
 'bebek',
 'beber',
 'beberapa',
 'beda',
 'begini',
 'begitu',
 'behavior',
 'bekal',
 'bela',
 'belaka',
 'belakang',
 'belanda',
 'belanja',
 'beli',
 'belum',
 'benam',
 'benar',
 'bencana',
 'bendung',
 'bengkel',
 'bentuk',
 'berangkat',
 'berani',
 'berapa',
 'berat',
 'beri',
 'berita',
 'berkah',
 'bersih',
 'bersunguh',
 'besar',
 'best',
 'betapa',
 'betul',
 'beyond',
 'biar',
 'biasa',
 'biaya',
 'bicara',
 'bidang',
 'bidik',
 'big',
 'bijak',
 'bikin',
 'bila',
 'bilang',
 'bill',
 'bina',
 'binatang',
 'biola',
 'bioskop',
 'biota',
 'bisa',
 'bisnis',
 'bitung',
 'blackberry',
 'bm',
 'boarding',
 'bogor',
 'bohong',
 'boleh',
 'bolmunt',
 'bolu',
 'booth',
 'box',
 'boy',
 'bpn',
 'brawijaya',
 'breathless',
 'brin',
 'brunei',
 'buah',
 'buas',
 'buat',
 'budaya',
 'buka',
 'bukan',
 'bukit',
 'bukti',
 'bulan',
 'bule',
 'bumi',
 'bunaken',
 'bunga',
 'bunuh',
 'burger',
 'buru',
 'busa',
 'business',
 'butuh',
 'by',
 'byme',
 'c1',
 'cabang',
 'cabin',
 'cadang',
 'cafe',
 'cagar',
 'cahari',
 'cakap',
 'caleg',
 'calendar',
 'calender',
 'call',
 'calon',
 'camat',
 'canda',
 'canggih',
 'cangkir',
 'capacity',
 'capai',
 'capres',
 'cara',
 'cari',
 'carry',
 'cartoon',
 'cat',
 'catat',
 'category',
 'cawapres',
 'cegah',
 'cek',
 'cemilan',
 'cenderung',
 'center',
 'ceo',
 'cepat',
 'cerdas',
 'cerita',
 'cermin',
 'cetak',
 'cetus',
 'chain',
 'charging',
 'chat',
 'chatting',
 'cheapcaribbean',
 'cheapcarribean',
 'check',
 'cheese',
 'chen',
 'chief',
 'china',
 'cincinnati',
 'cinta',
 'cipta',
 'ciri',
 'cium',
 'classic',
 'climbing',
 'cloud',
 'club',
 'cn',
 'co',
 'coat',
 'coattail',
 'coba',
 'coblos',
 'cocok',
 'coe',
 'com',
 'commerce',
 'communication',
 'consumer',
 'content',
 'control',
 'corporate',
 'count',
 'cruise',
 'cuaca',
 'cuci',
 'cukup',
 'culture',
 'curang',
 'cynthia',
 'daerah',
 'daftar',
 'daging',
 'dahulu',
 'daily',
 'dalam',
 'dampak',
 'dan',
 'dana',
 'daniel',
 'dapat',
 'dapil',
 'dapur',
 'dar',
 'darah',
 'darat',
 'dari',
 'daring',
 'daringnya',
 'daripada',
 'dark',
 'darussalam',
 'dasar',
 'data',
 'datang',
 'datar',
 'davao',
 'daya',
 'ded',
 'dekat',
 'dekorasi',
 'delay',
 'delta',
 'demi',
 'demikian',
 'demokrat',
 'dengan',
 'dengar',
 'denyut',
 'depan',
 'departure',
 'deputy',
 'deras',
 'derita',
 'desa',
 'desain',
 'desember',
 'design',
 'desk',
 'dessert',
 'destinasi',
 'detail',
 'deteksi',
 'develop',
 'developer',
 'development',
 'dewan',
 'dewasa',
 'dewata',
 'dewi',
 'di',
 'dia',
 'diberitahu',
 'didih',
 'didik',
 'dimensi',
 'din',
 'dinas',
 'dinding',
 'dingin',
 'direct',
 'direktorat',
 'diri',
 'disbudpar',
 'distribusi',
 'ditindaklanjuti',
 'diving',
 'divisi',
 'djoko',
 'dkppu',
 'do',
 'dolar',
 'dollar',
 'domestik',
 'dominan',
 'dong',
 'dorong',
 'down',
 'dpd',
 'dpt',
 'dpthp',
 'dr',
 'driven',
 'dua',
 'duduk',
 'duga',
 'dugaaan',
 'duka',
 'dukung',
 'dulu',
 'dulunya',
 'dunia',
 'duo',
 'ecek',
 'edar',
 'efek',
 'effect',
 'efisien',
 'eiffel',
 'ekonomi',
 'ekonomis',
 'ekor',
 'eksklusif',
 'eksplorasi',
 'ekstraksi',
 'ekstrem',
 'electronics',
 'elektoral',
 'email',
 'emisi',
 'emoji',
 'emosional',
 'empat',
 'enam',
 'energi',
 'enggak',
 'enggan',
 'engineer',
 'engineering',
 'enginering',
 'entah',
 'entri',
 'episode',
 'era',
 'eropa',
 'es',
 'estate',
 'etnis',
 'evakuasi',
 'event',
 'facebook',
 'factor',
 'fakta',
 'faktor',
 'fans',
 'farasya',
 'fasilitas',
 'favorit',
 'feed',
 'felicia',
 'felicity',
 'fenomena',
 'ferdian',
 'festival',
 'fi',
 'figure',
 'filipina',
 'first',
 'fisik',
 'fitur',
 'flight',
 'flightstatus',
 'florikultura',
 'flower',
 'fm',
 'fokus',
 'follower',
 'followers',
 'foods',
 'for',
 'foreign',
 'forensik',
 'form',
 'format',
 'forum',
 'fosil',
 'foto',
 'fotografer',
 'fotokopi',
 'four',
 'frekuensi',
 'frontend',
 'fu',
 'fungsi',
 'furqan',
 'gabung',
 'gajah',
 'gakkumdu',
 'galeri',
 'gambar',
 'game',
 'ganda',
 'gandeng',
 'gang',
 'ganggu',
 'ganti',
 'gantiang',
 'gantung',
 'ganxi',
 'garap',
 'garpu',
 'gas',
 'gates',
 'gaya',
 'gedung',
 'gelap',
 'gelar',
 'gelombang',
 'gemar',
 'gembala',
 'generasi',
 'genetik',
 'genpi',
 'geografis',
 'gera',
 'gerak',
 'gerindra',
 'geser',
 'gestur',
 'gg',
 'ghofar',
 'gianyar',
 'giat',
 'gif',
 'giling',
 'giora',
 'giring',
 'girl',
 'gitu',
 'giur',
 'gizi',
 'global',
 'golgota',
 'google',
 'gor',
 'goreng',
 'grandma',
 'gratis',
 'great',
 'group',
 'grup',
 'gudang',
 'gulden',
 'gulir',
 'guna',
 'gunung',
 'gurame',
 'gurau',
 'guru',
 'gusti',
 'gym',
 'habis',
 'hadap',
 'hadir',
 'hak',
 'hakim',
 'hal',
 'halaman',
 'halang',
 'halilintar',
 'hambat',
 'hampir',
 'hand',
 'handphone',
 'hangat',
 'hanya',
 'hapus',
 'harap',
 'harer',
 'harga',
 'hari',
 'harimau',
 'haru',
 'harus',
 'hasil',
 'hawa',
 'hayati',
 'helena',
 'help',
 'hemat',
 'heme',
 'hemoglobin',
 'hendak',
 'henti',
 'heran',
 'herwyn',
 'hewan',
 'hias',
 'hibur',
 'hidup',
 'hilang',
 'himpun',
 'hindar',
 'hingga',
 'hironobu',
 'hitam',
 'hitung',
 'hoaks',
 'holografik',
 'hong',
 'hormat',
 'hotspot',
 'hubung',
 'hujan',
 'hukum',
 'huni',
 'hutan',
 'ia',
 'icon',
 'id',
 'identifikasi',
 'if',
 'ikan',
 'ikhtiar',
 'ikon',
 'ikonik',
 'ikut',
 'ili',
 'ilmu',
 'imbau',
 'imbuh',
 'implikasi',
 'impor',
 'impossible',
 'in',
 'inap',
 'indah',
 'independen',
 'india',
 'indikasi',
 'indonesia',
 'industri',
 'influencer',
 'informasi',
 'informatika',
 'infrastruktur',
 'ingat',
 'inggris',
 'ingin',
 'ini',
 'inisiatif',
 'innocent',
 'input',
 'insentif',
 'insiden',
 'insider',
 'insinyur',
 'instagram',
 'instagramnya',
 'instan',
 'instansi',
 'institut',
 'instruksi',
 'integrasi',
 'integrated',
 'intelligence',
 'intensif',
 'interactive',
 'interaksi',
 'interaktif',
 'internal',
 'internasional',
 'international',
 'internet',
 'interogasi',
 'investasi',
 'iocc',
 'ios',
 'ipad',
 'iphone',
 'ir',
 'iresearch',
 'iring',
 'irregularities',
 'is',
 'isi',
 'iskandar',
 'ismail',
 'istimewa',
 'isu',
 'italianya',
 'item',
 'its',
 'itu',
 'izin',
 'jadi',
 'jadwal',
 'jaga',
 'jago',
 'jajal',
 'jajar',
 'jakarta',
 'jalan',
 'jalin',
 'jalur',
 'jam',
 'jamin',
 'jane',
 'jangan',
 'jangkau',
 'janji',
 'januari',
 'jarah',
 'jarak',
 'jarang',
 'jaring',
 'jas',
 'jasa',
 'jatuh',
 'jauh',
 'jawa',
 'jawab',
 'jd',
 'jejak',
 'jelang',
 'jelas',
 'jemur',
 'jenazah',
 'jenis',
 'jenjang',
 'jepang',
 'jerman',
 'jernhusen',
 'jerome',
 'jess',
 'jessica',
 'jika',
 'jinjing',
 'jiwa',
 'joko',
 'jokowi',
 'jorong',
 'jual',
 'juga',
 'jujur',
 'jujuran',
 'juli',
 'jumat',
 'jumlah',
 'jumpa',
 'junjiahao',
 'juru',
 'juruselamat',
 'just',
 'justru',
 'juta',
 'ka',
 'kabar',
 'kabin',
 'kabupaten',
 'kaca',
 'kacang',
 'kagum',
 'kait',
 'kala',
 'kalah',
 'kalang',
 'kalau',
 'kali',
 'kalian',
 'kalimantan',
 'kalo',
 'kamera',
 'kami',
 'kampanye',
 'kampung',
 'kampus',
 'kamu',
 'kan',
 'kanan',
 'kandung',
 'kantor',
 'kanye',
 'kapal',
 'kapan',
 'kapasitas',
 'kapel',
 'kapital',
 'kapolsek',
 'karakteristik',
 'karam',
 'kardashian',
 'karena',
 'kargo',
 'karibia',
 'karier',
 'kartu',
 'karyawan',
 'kasih',
 'kasihan',
 'kasus',
 'kata',
 'kategori',
 'katolik',
 'kaum',
 'kawal',
 'kawasan',
 'kaya',
 ...]

In [ ]:
print('Daftar Stopword:')
vectorizer.get_stop_words()

Daftar Stopword:

In [ ]:
print('Matriks Tf:')
tf_matrix = pd.DataFrame(tf.toarray(), columns=vectorizer.get_feature_names())
tf_matrix

Matriks Tf:

,00,000,02,03,030,04,08,09,10,100,...,yang,yerusalem,yesus,yogyakarta,yunani,zahid,zamih,zat,ziarah,zoetry
0,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,0,0,0,0,0,0
5,3,0,1,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,10,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,12,1,5,0,0,0,0,0,5,0
9,0,0,0,0,0,0,0,0,2,0,...,4,0,0,0,0,0,0,0,0,1
10,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,8,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,13,0,0,0,8,0,0,0,0,0
14,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,1,1,...,7,0,0,0,0,0,1,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,11,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,1,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
20,0,1,0,0,0,0,0,0,0,0,...,11,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,1,...,8,0,0,0,0,0,0,0,0,0
22,0,3,0,0,0,0,0,0,2,0,...,15,0,0,0,0,0,0,2,0,0
23,0,1,0,0,0,0,0,0,0,0,...,9,0,0,0,0,0,0,0,0,0
24,2,1,0,0,0,0,0,1,0,0,...,4,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
27,0,0,1,1,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
28,1,0,0,0,0,0,0,2,0,0,...,2,0,0,1,0,0,0,0,0,0
29,0,1,0,0,0,0,0,0,0,0,...,8,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,18,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,1,0,...,26,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,10,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,1,...,12,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,1,0,3,1,...,5,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,17,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0

In [ ]:
print('Matriks Tf (khusus data train):')
tf_train = tf_matrix[:n_train]
tf_train.shape

Matriks Tf (khusus data train):

(30, 2284)

In [ ]:
transformer = TfidfTransformer(sublinear_tf=True)

# Penyesuaian df agar query (data test) tidak dihitung pada perhitungan df
n = n_train
df = tf_train.astype(bool).sum(axis=0)
idf = np.log(n/df)
transformer.idf_ = idf

weight = transformer.fit_transform(tf)
print('Jumlah dokumen:', weight.shape[0])
print('Jumlah term:', weight.shape[1])

Jumlah dokumen: 40
Jumlah term: 2284

In [ ]:
weight_matrix = pd.DataFrame(weight.toarray(), columns=vectorizer.get_feature_names())
weight_matrix

,00,000,02,03,030,04,08,09,10,100,...,yang,yerusalem,yesus,yogyakarta,yunani,zahid,zamih,zat,ziarah,zoetry
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.066301,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.069377,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.044423,0.00000,0.000000,0.000000,0.000000,0.074844,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059516,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.060025,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.105043,0.000000,0.058290,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.047502,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.050314,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.056157,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.057495,0.06633,0.173084,0.000000,0.000000,0.000000,0.000000,0.000000,0.173084,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.103580,0.000000,...,0.049963,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.084178
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.068396,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.060575,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.051404,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.070304,0.00000,0.000000,0.000000,0.244157,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.082367,0.000000,0.000000,0.000000,0.106681,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.026535,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.051800,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063004,0.066936,...,0.063524,0.00000,0.000000,0.000000,0.000000,0.000000,0.086694,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.055666,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.068489,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.092533,0.000000,0.000000,0.000000,0.000000,...,0.038969,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.045015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.052350,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.059758,...,0.059282,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.078844,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063610,0.000000,...,0.047679,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.087528,0.000000,0.000000
23,0.000000,0.049795,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.054489,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.104742,0.058229,0.000000,0.000000,0.000000,0.000000,0.000000,0.072042,0.000000,0.000000,...,0.047556,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.073148,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059226,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.079094,0.087965,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.057093,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.074354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.146610,0.000000,0.000000,...,0.040556,0.00000,0.000000,0.096302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.059530,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.062742,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.059798,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.034601,0.000000,...,0.050426,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.063668,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.048507,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.058838,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060050,...,0.067416,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068029,0.000000,0.103755,0.052525,...,0.044154,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.060538,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.051090,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.055079,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
# Pembagian matriks bobot
weight_train = weight_matrix[:n_train]
weight_test = weight_matrix[n_train:]

### Perhitungan Cosine Similarity

In [ ]:
# Perhitungan cosine similarity
cosim = cosine_similarity(weight_train, weight_test)
print('Ukuran matriks cosine similarity: ', cosim.shape)

Ukuran matriks cosine similarity:  (30, 10)

In [ ]:
name = []
for i in range(n_test):
  name.append('Dokumen ' + str(i))

In [ ]:
# Baris = dokumen train, Kolom = dokumen test
print('Matriks Cosine Similarity:')
cosim_matrix = pd.DataFrame(cosim, columns=name)
cosim_matrix.shape

Matriks Cosine Similarity:

(30, 10)

In [ ]:
# Cosim Matrix + Label
cosim_matrix['Label Train'] = train_data['label'].values
label_row = dict(zip(name, test_data['label'].values))
label_cosim = cosim_matrix.append(label_row, ignore_index=True)
label_cosim.rename({label_cosim.index[-1]:'Label Test'}, inplace=True)

label_test = pd.DataFrame(label_cosim.iloc[-1])
label_test = label_test.T
label_test

,Dokumen 0,Dokumen 1,Dokumen 2,Dokumen 3,Dokumen 4,Dokumen 5,Dokumen 6,Dokumen 7,Dokumen 8,Dokumen 9,Label Train
Label Test,Teknologi,Teknologi,Politik,Travel,Politik,Teknologi,Travel,Teknologi,Travel,Travel,NaN

In [ ]:
label_cosim

,Dokumen 0,Dokumen 1,Dokumen 2,Dokumen 3,Dokumen 4,Dokumen 5,Dokumen 6,Dokumen 7,Dokumen 8,Dokumen 9,Label Train
0,0.166523,0.125987,0.251644,0.0973246,0.121499,0.0881351,0.0810806,0.0875771,0.0817409,0.0599243,Teknologi
1,0.0760685,0.0858697,0.182546,0.0869399,0.0981643,0.0543936,0.0583188,0.0451769,0.0574865,0.0425029,Politik
2,0.0609758,0.0776311,0.0438048,0.12774,0.0444317,0.0744816,0.113667,0.0407356,0.0677027,0.062158,Travel
3,0.078341,0.094299,0.182418,0.0914816,0.0684309,0.0776131,0.0673495,0.055803,0.0637513,0.0543963,Politik
4,0.0764908,0.10425,0.0696865,0.0663873,0.0475658,0.0906005,0.0602488,0.0664026,0.0703064,0.0800367,Travel
5,0.127565,0.16722,0.143201,0.102751,0.0667467,0.105445,0.118526,0.114682,0.111002,0.076542,Politik
6,0.113296,0.120224,0.0728179,0.085999,0.0408695,0.0878792,0.0588184,0.184536,0.136251,0.0860654,Teknologi
7,0.156922,0.141301,0.137956,0.13048,0.0613107,0.0992285,0.088209,0.155896,0.120633,0.0854708,Teknologi
8,0.0969691,0.118859,0.0836936,0.109936,0.0748589,0.0980873,0.0873071,0.0888245,0.0959088,0.130477,Travel
9,0.0879894,0.125724,0.089263,0.108286,0.0772156,0.0829777,0.115987,0.08931,0.146899,0.145044,Travel
10,0.135413,0.149698,0.073117,0.0858868,0.0551438,0.0974257,0.0851202,0.231037,0.116065,0.105827,Teknologi
11,0.120064,0.124848,0.0533598,0.0740463,0.0501979,0.0855787,0.0670601,0.104442,0.0787707,0.0748602,Teknologi
12,0.0919513,0.0932207,0.0607923,0.168457,0.0821657,0.0652805,0.0700821,0.0690627,0.206796,0.0711703,Travel
13,0.131467,0.120385,0.111689,0.130991,0.0802303,0.117663,0.127464,0.0995646,0.0925133,0.134929,Travel
14,0.0440797,0.0588327,0.229396,0.0639697,0.090953,0.0509469,0.056212,0.0321011,0.0725462,0.0191282,Politik
15,0.118453,0.159978,0.0816706,0.104064,0.0823751,0.118035,0.0854823,0.0908597,0.225624,0.127995,Travel
16,0.11106,0.106782,0.0524028,0.0796629,0.0492929,0.0649222,0.0983195,0.0675553,0.0755031,0.0951416,Travel
17,0.107017,0.134609,0.0825875,0.086918,0.0617143,0.0631811,0.0757037,0.0684042,0.102786,0.0568358,Teknologi
18,0.0841349,0.111906,0.248478,0.117701,0.114403,0.0955877,0.0692934,0.0649866,0.115972,0.0616713,Politik
19,0.0606964,0.0820662,0.0632866,0.149628,0.081633,0.0717838,0.0524412,0.0654759,0.170636,0.100048,Travel
20,0.10727,0.112958,0.0734212,0.15329,0.0685595,0.192493,0.118366,0.0707539,0.122705,0.0681798,Teknologi
21,0.123009,0.114276,0.0633616,0.0732144,0.0521255,0.0971173,0.0706397,0.124632,0.131877,0.0778337,Teknologi
22,0.156491,0.141761,0.0841151,0.133219,0.0669742,0.14491,0.139182,0.0777264,0.122174,0.0908598,Teknologi
23,0.105582,0.146362,0.108986,0.091505,0.0708825,0.110593,0.109262,0.0986127,0.117634,0.083107,Travel
24,0.0864948,0.094573,0.0645105,0.0990678,0.0430662,0.0917128,0.0730791,0.0759908,0.10678,0.0967872,Travel
25,0.074086,0.0920079,0.075131,0.0811507,0.0568148,0.0675752,0.0632116,0.16181,0.0912098,0.103926,Teknologi
26,0.0523561,0.0715975,0.117535,0.140688,0.122994,0.0400659,0.160834,0.0406699,0.036962,0.0475062,Politik
27,0.0980067,0.0931577,0.107642,0.0879928,0.13313,0.0546249,0.097231,0.0503107,0.0979508,0.0571354,Politik
28,0.0404378,0.0660444,0.0991936,0.046086,0.0732152,0.062841,0.0370348,0.051175,0.0355559,0.0822015,Politik
29,0.167881,0.137535,0.0966567,0.100815,0.0841918,0.125614,0.105426,0.15519,0.101156,0.0773895,Teknologi
Label Test,Teknologi,Teknologi,Politik,Travel,Politik,Teknologi,Travel,Teknologi,Travel,Travel,NaN

### Evaluasi

In [ ]:
def average_precision(cosim_matrix, n_retrieve):
  average_precision = []

  # Loop untuk mengambil setiap query di cosim matrix
  for column in cosim_matrix.iloc[:, :-1]:

    # Sort and get top n
    sorted_cosim = cosim_matrix.sort_values(column, ascending=False)
    top_n = sorted_cosim.iloc[:n_retrieve]
#     print(top_n)

    # List of relevance
    relevant = (np.array(top_n['Label Train']) == np.array(label_test[column]))
#     print(relevant)

    # List of precision
    precision = []
    peringkat = 0
    counter_relevant = 0

    for r in relevant:
      peringkat += 1
      if r == True:
        counter_relevant += 1
        precision.append(counter_relevant / peringkat)

    # List of average precision
    average_precision.append(np.mean(precision))

  return average_precision

def mean_average_precision(cosim_matrix, n_retrieve):
  ap = average_precision(cosim_matrix, n_retrieve)
  map = np.mean(ap)
  return map

def precision_at_k(cosim_matrix, k_retrieve):
  precision_at_k = []

  # Loop untuk mengambil setiap query di cosim matrix
  for column in cosim_matrix.iloc[:, :-1]:

    # Sort and get top n
    sorted_cosim = cosim_matrix.sort_values(column, ascending=False)
    top_n = sorted_cosim.iloc[:k_retrieve]
#     print(top_n)

    # List of relevance
    relevant = (np.array(top_n['Label Train']) == np.array(label_test[column]))
#     print(relevant)

    # List of precision
    precision = np.sum(relevant) / len(relevant)
    precision_at_k.append(precision)

  return precision_at_k

def r_precision(cosim_matrix, n_retrieve):
  r_precision = []

  # Loop untuk mengambil setiap query di cosim matrix
  for column in cosim_matrix.iloc[:, :-1]:

    # Sort and get top n
    sorted_cosim = cosim_matrix.sort_values(column, ascending=False)
    top_n = sorted_cosim.iloc[:n_retrieve]
#     print(top_n)

    # List of relevance
    relevant = (np.array(top_n['Label Train']) == np.array(label_test[column]))
#     print(relevant)

    # List of precision
    precision = np.sum(relevant) / len(relevant)
    r_precision.append(precision)

  return r_precision

In [ ]:
print('Hasil Evaluasi MAP: ', mean_average_precision(cosim_matrix, 10))
print('Hasil Evaluasi Precision@K: ', precision_at_k(cosim_matrix, 10))
print('Hasil Evaluasi R-Precision: ', r_precision(cosim_matrix, 10))

Hasil Evaluasi MAP:  0.7668191609977324
Hasil Evaluasi Precision@K:  [0.7, 0.6, 0.6, 0.5, 0.5, 0.5, 0.5, 0.7, 0.5, 0.7]
Hasil Evaluasi R-Precision:  [0.7, 0.6, 0.6, 0.5, 0.5, 0.5, 0.5, 0.7, 0.5, 0.7]